# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  build:
    docker:
      - image: circleci/node:12.16.1-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.16.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # install dependencies
      - run: sudo npm install -g npm
      - run: npm install
      # cache node_modules
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run:
          name: unit tests
          command: node --max_old_space_size=5120 ./node_modules/@angular/cli/bin/ng test  --max-workers=1
#     # run local e2e tests
#      - run:
#          name: install cypress
#          command: npm install cypress
#      - run:
#          name: local e2e tests
#          command: node --max_old_space_size=5120 ./node_modules/angular-http-server/lib/angular-http-server --path ./dist -p 4200 http://localhost:4200 cypress run
      # upload coverage
      - run:
          name: generate and upload coverage
          command: npm run sendcoverage

  build-staging:
      docker:
        # specify the version you desire here
        - image: circleci/node:12.16.1-browsers

      working_directory: ~/repo

      steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        # install dependencies
        - run: sudo npm install -g npm
        #- run: sudo npm install angular-cli@latest -g
        - run: npm install
        # cache node_modules
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}


        # build production
        # yarn ng build --prod --configuration=production
        - run:
            name: build staging
            command: |
              mkdir -p ~/repo/workspace/deploy
              mkdir -p ~/repo/workspace/dist
              node ./node_modules/@angular/cli/bin/ng build --configuration=staging --build-optimizer --aot --optimization
              ls -lh ~/repo
              cp -r ~/repo/dist/* ~/repo/workspace/dist
              cp  ~/repo/.circleci/deploy.sh ~/repo/workspace/deploy/
        - persist_to_workspace:
            root: workspace
            paths:
              - ./
        - store_artifacts:
            path: ~/repo/workspace/dist/
            destination: app-distribution
  build-ci:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.16.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install dependencies
      - run: sudo npm install -g npm
      #- run: sudo npm install angular-cli@latest -g
      - run: npm install
      # cache node_modules
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      # build production
      # yarn ng build --prod --configuration=production
      - run:
          name: build ci
          command: |
            mkdir -p ~/repo/workspace/deploy
            mkdir -p ~/repo/workspace/dist
            node ./node_modules/@angular/cli/bin/ng build --configuration=ci --build-optimizer --aot --optimization
            ls -lh ~/repo
            cp -r ~/repo/dist/* ~/repo/workspace/dist
            cp  ~/repo/.circleci/deploy.sh ~/repo/workspace/deploy/
      - persist_to_workspace:
          root: workspace
          paths:
            - ./
      - store_artifacts:
          path: ~/repo/workspace/dist/
          destination: app-ci-distribution
  build-prod:
      docker:
        # specify the version you desire here
        - image: circleci/node:12.16.1-browsers

      working_directory: ~/repo

      steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        # install dependencies
        - run: sudo npm install -g npm
        #- run: sudo npm install angular-cli@latest -g
        - run: npm install
        # cache node_modules
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}


        # build production
        - run:
            name: build production
            command: |
              mkdir -p ~/repo/workspace/deploy
              mkdir -p ~/repo/workspace/dist
              node ./node_modules/@angular/cli/bin/ng build --configuration=production --build-optimizer --aot --optimization
              ls -lh ~/repo
              cp -r ~/repo/dist/* ~/repo/workspace/dist
              cp  ~/repo/.circleci/deploy.sh ~/repo/workspace/deploy/
        - persist_to_workspace:
            root: workspace
            paths:
              - ./
        - store_artifacts:
            path: ~/repo/workspace/dist/
            destination: app-distribution

  test-e2e:
    docker:
      - image: circleci/node:12.16.1-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: install cypress
          command: npm install cypress
      - run:
          name: remote e2e tests
          command: node --max_old_space_size=5120 CYPRESS_BASE_URL=https://ci-app.mccullough-solutions.ca ./node_modules/cypress/bin/cypress run



  deploy-ci:
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo/workspace
      # install dependencies
      - run:
          context: ci
          name: install AWS
          command: |
            sudo apt-get install jq
            sudo pip install awscli
            aws --version
            echo access key: $AWS_ACCESS_KEY_ID
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region ca-central-1
            aws configure set default.output json
      # deploy staging
      - run: ls -lh
      - run:
          context: ci
          name: deploy build (ci)
          command: |
            ls -lh ~/repo/
            ls -lh ~/repo/workspace/
            chmod 744 ~/repo/workspace/deploy/deploy.sh
            ~/repo/workspace/deploy/deploy.sh ci
  deploy-staging:
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo/workspace
      # install dependencies
      - run:
         context: staging
         name: install AWS
         command: |
           sudo apt-get install jq
           sudo pip install awscli
           aws --version
           echo access key: $AWS_ACCESS_KEY_ID
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
           aws configure set region ca-central-1
           aws configure set default.output json
      # deploy staging
      - run: ls -lh
      - run:
         context: staging
         name: deploy build (staging)
         command: |
           ls -lh ~/repo/
           ls -lh ~/repo/workspace/
           chmod 744 ~/repo/workspace/deploy/deploy.sh
           ~/repo/workspace/deploy/deploy.sh staging

  deploy-prod:
      docker:
        - image: circleci/python:3.6-jessie

      working_directory: ~/repo
      steps:
            - attach_workspace:
                at: ~/repo/workspace
            # install dependencies
            - run:
               context: prod
               name: install AWS
               command: |
                 sudo apt-get install jq
                 sudo pip install awscli
                 aws --version
                 aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                 aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                 aws configure set region ca-central-1
                 aws configure set default.output json
            # deploy production
            - run:
               context: prod
               name: deploy build (production)
               command: |
                 ls -lh ~/repo/
                 ls -lh ~/repo/workspace/
                 chmod 744 ~/repo/workspace/deploy/deploy.sh
                 ~/repo/workspace/deploy/deploy.sh prod


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - build-ci:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
          context: ci
      - deploy-ci:
          requires:
            - build
            - build-ci
          filters:
            branches:
              only: develop
          context: ci
      - test-e2e:
          requires:
            - deploy-ci
          filters:
            branches:
              only: develop
      - build-staging:
          requires:
            - build
            - build-ci
            - deploy-ci
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*[/]Stage[/]build_.*/
            branches:
              ignore: /.*/
          context: staging
      - deploy-staging:
          requires:
            - build
            - build-staging
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*[/]Stage[/]build_.*/
            branches:
              ignore: /.*/
          context: staging
      - build-prod:
          requires:
            - build
          filters:
            branches:
              only:
                - master
          context: staging
      - hold:
          type: approval
          requires:
            - build-prod
          filters:
            branches:
              only: master
          context: prod
      - deploy-prod:
          requires:
            - build
            - build-prod
          filters:
            branches:
              only: master
          context: prod



